### ISSUE TITLE
Won't update Opening Hours 

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#1006]
When editing a toilet page, if I enter opening hours, the 'Update the toilet' button does not do anything.
If I make edits but leave opening hours as unknown, it updates.

is there a particular format that these need entering in, to make it work? 

Using Safari on desktop. 

(it was this toilet https://www.toiletmap.org.uk/loos/27c1892458a07c7e7e3089aa - I've abandoned edits before when they wouldn't submit, I think for same reason, but just pinpointed the opening hours as likely problem)

**Comment by marxian** [comment]
@gailramster I found some issues in opening hours, and I've deployed a new release.

However, I'm interested i your question "is there a particular format that these need entering in, to make it work?"

Do you not see a pair of 24hour time pickers for the opening and closing time on each day?

**Comment by gailramster** [comment]
Ah! No. 

Safari 13.1.2

![Screen Shot 2021-02-01 at 12 38 31](https://user-images.githubusercontent.com/2690575/106460089-b501f180-648a-11eb-9d6a-afb633e609da.png)

I've just checked on Chrome and can see them now - but I always use Safari..

**Comment by marxian** [comment]
Fascinating :-)

I'll look into it :-)
