### ISSUE TITLE
Cannot close a toilet on a certain day (opening hours)

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#1037]
The toggle switch to turn a toilet from 'closed' to 'opening hours' on a certain day, does not turn off again. 

I've tried deleting the numbers in the opening hours field, and clicking 'update toilet' to try to close a toilet on that day. This doesn't load a new page to confirm that the toilet has been updated - it stays on the edit page. 

Though the toggle button looks squished on Safari, this happens on both Safari and Chrome. 

e.g. https://www.toiletmap.org.uk/loos/3d96d12c38bf7edb22624957/edit
This cafe at Westminster Central Hall is closed on Sat & Sun. I 'opened' it on Saturdays to test the opening hours, and now I cannot close it again!

![Screen Shot 2021-03-29 at 10 02 54](https://user-images.githubusercontent.com/2690575/112814666-7007cf00-9077-11eb-8712-78f40fd938f3.png)
![Screen Shot 2021-03-29 at 10 03 16](https://user-images.githubusercontent.com/2690575/112814676-7138fc00-9077-11eb-9eef-4ce812afc8bc.png)

**Comment by ob6160** [comment]
hey Gail, will take a look!
