### ISSUE TITLE
Upload User Guidance + Checklist (asap!)

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#1265]
AgeUK London are running a campaign NEXT WEEK that includes proposing older Londoners volunteer to edit the map.

To support this, I have made a user guide for people who want one, and 'out-and-about checklist' for people who want to edit it once back home.

AgeUK London need links asap to put in their newsletter to 25000 people next week.

These need to be - ideally - available on toiletmap.org.uk - with a sentence about what they are, for AgeUK to point to, and for people to download. 

They're not London-specific, that's just the catalyst.

[GBPTM Toilet Checklist.pdf](https://github.com/neontribe/gbptm/files/7688195/GBPTM.Toilet.Checklist.pdf)
[Toilet Map Volunteer Help Guide .pdf](https://github.com/neontribe/gbptm/files/7688197/Toilet.Map.Volunteer.Help.Guide.pdf)

**Comment by ob6160** [comment]
@gailramster  I've opened a code change here: https://github.com/neontribe/gbptm/pull/1277, please let me know if the copy in the screenshot looks alright 🙂
