### ISSUE TITLE
Fix the local database, add fixtures

### ISSUE THREAD

**Issue by ob6160** [neontribe/gbptm#1293]

**Comment by andrejusk** [comment]
Heya @ob6160, thanks for raising this. Would you mind filling in a bit more detail about your current approach to:

- Local runner script -- I can see that the README.md currently says `yarn dev`
- Local runner's store (is it hitting anything remote?)
- Local runner's auth (is it dependant on anything remote?)
- Store fixtures (are there any? how/when do they get applied?)

I'm exploring the possibility of producing a Docker image as output and I'd like to introduce a few helper scripts to make local development a breeze that fits well with the current approach. It's something I've recently worked on for my recent projects, and would be happy to try my hand at introcing here as well.
