### ISSUE TITLE
Chrome  - Location not being asked for 

### ISSUE THREAD

**Issue by jermyk** [neontribe/gbptm#176]
User was on Chrome desktop

Went to  https://gbptm-unity.herokuapp.com. Logged in however was not asked of location whereabouts

Also happened on IE11

**Comment by marxian** [comment]
I can't seem to replicate this on chrome (linux)

**Comment by harryharrold** [comment]
Tested on machine that had never visited the site - MacOS/Chrome - couldn't replicate. Permission asked for, granted, used.
