### ISSUE TITLE
Testing questions/Issues

### ISSUE THREAD

**Issue by jermyk** [neontribe/gbptm#179]
- [x] IE11 Toilet pin doesn't fire?
- [x] Toilet preferences doesn't seem to do anything eg Gurney Road toilets doesn't have baby changing but appears on map after making preference.
- [x] Map centre dot might get confused for a loo?
- [x] Where does initial data come from 
- [ ] Styling of More info on Firefox eg St. Andrews.
- [x] Updating credentials ?

**Comment by marxian** [comment]
When you select a toilet pin from the main map or list you should navigate to that loo's page e.g:

https://gbptm-unity.herokuapp.com/loos/57077f0a4503a31000e45c31

**Comment by jermyk** [comment]
**Login**

**Comment by jermyk** [comment]
**Preferences**

**Comment by jermyk** [comment]
**Pins**

**Comment by jermyk** [comment]
**Editing**

**Comment by jermyk** [comment]
**Nearest Toilets**

- [ ] Firefox - No scroll on Nearest Toilets selection

**Comment by jermyk** [comment]
**Map**

- [ ] IE11 Show me where I am - Not firing.
