### ISSUE TITLE
API incorrectly calculates what loos are in a given radius / bounding box

### ISSUE THREAD

**Issue by Hoolean** [neontribe/gbptm#186]
## Problem

At present, [metres are converted into radians](https://github.com/neontribe/gbptm/blob/3a26cc28441c67dc9cf3907808155fe9d9e3f728/packages/api/src/models/loo.js#L15) before being passed to Mongo's `$geoNear`.

We don't really want to represent our distance as radians while providing an interface that uses metres, however, as the amount of metres a radian represents in longitude varies greatly at different latitudes. Our simple conversion method doesn't take this into account and so the results returned are misleading.

As we use `$geoNear` with a radius to do our bounding box queries too, using [the same method of conversion](https://github.com/neontribe/gbptm/blob/3a26cc28441c67dc9cf3907808155fe9d9e3f728/packages/api/src/models/loo.js#L60), searches within a bounding box of coordinates are also affected.

## Suggested Remedy

Do we want to be using metres for toilet range searches in our API?

* For nearby toilets, almost definitely, as this represents how accessible toilets are for a user far better than coordinates could. [Mongo](https://docs.mongodb.com/manual/reference/operator/aggregation/geoNear/#definition) has support for metre radii, which we should try and use here.
* For coordinate bounds, it is more complicated. We should see how this could be used on the front-end before fixing this implementation but, to fix this, either:
  * The approach for nearby toilets could be used as previously (and clipped to the bounding box, which is _not_ done at the moment, although this is a separate issue) **or**
  * Simple numerical conditions could be tested against the toilet's coordinates (greater than / less than) to eliminate toilets outside the bounds, assuming they are rectangular, which is not checked for at present)

**Comment by marxian** [comment]
After some discussion:

Let's:

a) Make an attempt to talk radii in meters all the way through.
b) Immediately remove the `/in/<bbox>` endpoint and all its supporting code, until we can prove a use-case for it.
