### ISSUE TITLE
AddEditLooPage is mistitled in edit mode

### ISSUE THREAD

**Issue by marxian** [neontribe/gbptm#200]
We use the same component for add/edit, and it works, but it renders the same headings/rubric in both modes.

I suggest a `mode` prop we can pass in from `index.js`

**Comment by Hoolean** [comment]
Modal title implemented in 69ccc74. This can be easily extended to encompass the notification and other textual content if necessary before merging.

We already had a way of determining the mode [through the presence of the `loo` property](https://github.com/neontribe/gbptm/blob/4daf63bbf2c07a45c29ae3d2e171e032b25a1b12/packages/ui/src/pages/AddEditPage.js#L448-L450) and were using this to vary the form in other places already, so it was possible to avoid adding a `mode` property.

**Comment by Hoolean** [comment]
Title fixed by #205.
