### ISSUE TITLE
Our UI's back button behaviour can be confusing

### ISSUE THREAD

**Issue by Hoolean** [neontribe/gbptm#217]
## Quirks

* **Pressing our Back button having just submitted a loo report takes you back to the loo form**
A user would probably expect to be taken back to the home page, as this is normally what happens when they click on our Back button on a single loo's page.
* **Pressing our Back button after navigating directly to a route takes you away from the site completely**
A user would, again, probably expect to end up on the home page after initially navigating to `/report` in their address bar, not their new tab/home page/etc.

Most of what seems unsettling about the Back button is that a user would expect it to behave in a consistent way within the app, always taking them a layer shallower within their route. Instead, it behaves more like the browser's back button.

## Potential Solutions

* Always take the user roughly a layer shallower in our routes _or_
* Replace our Back button with buttons that are unambiguous about where they take you

**Comment by marxian** [comment]
obseleted
