### ISSUE TITLE
Research - Invoking navigation features across devices

### ISSUE THREAD

**Issue by marxian** [neontribe/gbptm#218]
We'd like to help users actually _get_to_ the loo

Can we invoke google maps in navigation mode from a link which Android will accept as an `intent`
Can we give a good experience with this on iOS and in desktop browsers

**Comment by Hoolean** [comment]
## Fear and Loathing in Map Linking

There is [a beautiful and standardised protocol](https://en.wikipedia.org/wiki/Geo_URI_scheme) for describing coordinates with URIs. Predictably, it is also unimplemented on an abundance of commonly used platforms as of now, including:
* Desktop Chromium
* Desktop Firefox
... despite prompting for the native app on, at least, Android.

[Apple provides a URI](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html#//apple_ref/doc/uid/TP40007899-CH5-SW1) but this is only implemented within their own ecosystem.

[Google Maps provides a plethora of URLs](https://developers.google.com/maps/documentation/urls/guide) for a variety of behaviours, including directions.
* On all desktops, the Google Maps website functions as expected
* On Android phones with Google Maps installed, it can be opened.
* On Apple devices, the user is presented with the web version of Google Maps but with the addition of banner ads trying to get the user to download the app

## The Best Bet

[Apple provide their own URLs](https://developer.apple.com/library/archive/featuredarticles/iPhoneURLScheme_Reference/MapLinks/MapLinks.html) that will open with their native app within their ecosystem else redirect to Google Maps. This has the effect that:
* On Apple devices, Apple Maps is opened
* On non-Apple desktops, the web Google Maps is opened
* On other non-Apple devices, the web Google Maps is opened, and this may trigger the opening of the native app

Trusting that Apple will not be predatory and stop redirecting to Google following the launch of their own web service, this is probably the best way forward.
