### ISSUE TITLE
Crosshair vanishes when editing location

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#220]
When you click 'edit this toilet' the crosshair briefly appears and tracks to the current location, but is never seen again even if map is moved. (Safari 11.1)

**Comment by marxian** [comment]
I have no idea how the crosshair gets shown at all, and I've looked pretty hard.

There's a `showCrosshair` prop on `LooMap` but it seems inert.

**Comment by marxian** [comment]
Looks like some of the original support was here:

https://github.com/neontribe/gbptm/blob/0a607eb29d7c97e9238a7e1c80dc4a51dea0921a/packages/ui/src/components/css/edit-loo-map.module.css

But this code wasn't working...
