### ISSUE TITLE
Bouncing green pin

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#221]
I've a toilet pin bouncing in green on my map, despite clicking others and going back several times - I don't know what it's trying to indicate.

**Comment by gailramster** [comment]
I've figured it out that it's the one I'm hovering on, on the left=hand tab. 
The tabs could be improved if they showed the Toilet Name, where available, so you instantly know what they are. (we may have to limit the length of name from now on if so..)

**Comment by gailramster** [comment]
The green pin is stuck again even if I hover over thumbnails on left.. not sure what it is. 

As we now have a back button and only one pin showing once you've clicked on a thumbnail, and no numbers, it's hard to track which thumbnail related to which pin again. Thumbnails that include toilet names, or two-way highlighting (so if I hover over a pin the thumbnail flashes, as well as vice-versa with the bouncing pin), could help.

**Comment by marxian** [comment]
The pin getting stuck in bounce mode is definitely a bug.

Suggested remedy: Clear the highligting in the store on homepage's componentDidUnmount
