### ISSUE TITLE
Handle absence of geolocation abilities

### ISSUE THREAD

**Issue by Hoolean** [neontribe/gbptm#235]
## Problem

At the moment, a user cannot use our app at all if they have geolocation disabled; they are taken to a screen that informs them that geolocation is not enabled. This is in spite of the fact that our application can still be useful without knowing the user's current location.

## Thoughts

* Where do we start the user if not at their current location?
* Should we point the user at the search bar before showing them a map at all in this scenario?

**Comment by harryharrold** [comment]
"Should we point the user at the search bar before showing them a map at all in this scenario?" - I like this thought. Try this and test it, I think?

**Comment by gailramster** [comment]
Happens with links via facebook without asking if i wish to use my location
