### ISSUE TITLE
The user can move around on a single loo page by zooming

### ISSUE THREAD

**Issue by Hoolean** [neontribe/gbptm#237]
## Problem

We don't let a user drag the map around when they are only viewing a single loo, however, by zooming out and then zooming in to another location, they can move around the map.

## Suggested Remedy

There is no real reason to disallow the user moving around the map freely on single loo mode other than that it may be unclear which loo marker the data is describing and where this marker is.

Consider the legacy GBPTM implementation; the user may move around but the loo they are looking at is clearly marked. Perhaps the user could be permitted to navigate around in single loo mode following the resolution of #229?

**Comment by marxian** [comment]
I'm tackling this as part of #228
