### ISSUE TITLE
Pressing "Update the toilet" having made no changes does nothing

### ISSUE THREAD

**Issue by Hoolean** [neontribe/gbptm#238]
## Problem

When the user edits a toilet but makes no changes, the "Update the toilet" button does nothing. While it is good that we don't issue an empty report, it is undesirable that nothing happens in the UI.

## Reproducing

1. Edit a toilet
1. Change nothing
1. Press the "Update the toilet" button
1. Nothing happens

## Potential Remedies

* Tell the user that they have not changed anything _or_
* Just go back to the loo's page

**Comment by marxian** [comment]
I suggest we disable the submit button when there's nothing to save...

**Comment by Hoolean** [comment]
The [`obvious-update-prevention`](https://github.com/neontribe/gbptm/tree/obvious-update-prevention) branch will only enable the button after the form's state is changed. This needs some styling to resolve the issue.

#255 was also discovered in the process of adding this change; please bear that in mind if testing the branch.
