### ISSUE TITLE
Loo page of removed loos is unclear

### ISSUE THREAD

**Issue by Hoolean** [neontribe/gbptm#244]
## Problems

The user can still navigate to the page of a removed loo. Unfortunately, we omit some useful information:
1. Location is not shown on the map
1. No labeling to show that the loo is removed
1. Removal reason, if previously provided, is not shown under a useful label
1. The user can edit the removed loo and even remove it again

**Comment by gailramster** [comment]
This also happens in GBPTM Explorer - e.g. I removed most toilets with 'hotel' as a search term, but they are still listed in explorer results days later (with no pin, and field 'removed' showing). 
Sharing for info - not a big problem (though needs fixing some time for moderator ease), but may be related?
