### ISSUE TITLE
Only Thin Strip of Map Displayed on Older Android Phones

### ISSUE THREAD

**Issue by pw3032** [neontribe/gbptm#257]
5inch screen. Android 5.1.1

**Comment by pw3032** [comment]
Hi
Rather worse than that ( screenshot attached )
Phillip

Sent from Yahoo Mail on Android 
 
  On Mon, 16 Jul 2018 at 11:26, Harry Dalton<notifications@github.com> wrote:   
Hi, thanks for the issue.

We have a known bug with styling on small screens at #236, is the screenshot there consistent with the bug you saw?

**Comment by Hoolean** [comment]
Nevermind about that screenshot, I think I've been able to replicate the issue.

![image](https://user-images.githubusercontent.com/2150762/42767811-e3e339ee-8915-11e8-8007-005ab75e3500.png)

**Comment by Hoolean** [comment]
@falconx Seems like 6294c715c739eaa9e6c11e75d6a953fd992456e0 is the breaking commit; do you know how we could fix this without reintroducing the IE bug?

**Comment by pw3032** [comment]
Hi Harry

Sorry I'm at work during the day so I can only do responses in the evenings.

If you need another screenshot drop me an email.

Yours

Phillip

--------------------------------------------
On Mon, 16/7/18, Harry Dalton <notifications@github.com> wrote:

 Subject: Re: [neontribe/gbptm] Only Thin Strip of Map Displayed on Android Smartphone (#257)
 To: "neontribe/gbptm" <gbptm@noreply.github.com>
 Cc: "pw3032" <pw3032@yahoo.co.uk>, "Author" <author@noreply.github.com>
 Date: Monday, 16 July, 2018, 16:33
 
 Nevermind about that screenshot,
 I think I've been able to replicate the issue.
 
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by Hoolean** [comment]
## Additional Reproduction

The same issue appears to be present on the iPhone 5S (see #267).
I can also reproduce this when triggering the small-viewport view on desktop in Firefox.
