### ISSUE TITLE
Cannot pan map in toilet report view

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#266]
When viewing a toilet report, other toilet pins now show (helpful) but you cannot pan the map. This was a useful feature to identify where the toilet is in relation to you, when trying to find it, and to find the next nearest toilet to you (from Phillip's feedback). 
Can it be reactivated or is there a design-reason for locking the map?

**Comment by gailramster** [comment]
If it can't be reactivated, then I think we need a back button (again) or better yet home button (that returns to their previous map view location). 

Currently once at a toilet report level, it's easy to feel trapped where the site has limited functionality - i.e. you can click from one toilet to another within that small map view (assuming there are other pins within that view - probably only true in cities) but you're unable to zoom out and explore and renavigate (even to check where the toilet is in relation to you - also why we need the 'you're location' spot on this map) except by searching for a term (which may not be what the user wants), or clicking the logo (which isn't signposted or intuitive for a new user - but does return you to your last map view, rather than reset the map, which is brill)

**Comment by Hoolean** [comment]
This is something I've been wondering too, as it would certainly be more consistent for the map to offer the same interaction across all pages.

Aside from the possibility of it getting confusing if the selected loo was dragged offscreen, I can't see why we shouldn't let people pan everywhere. I'll see what the reasoning was behind changing this behaviour in the new loo map iteration and report back.

**Comment by gailramster** [comment]
Thanks. just to add I think both Phillip and I are using the map on a desktop when looking for this feature - though it would be helpful for figuring out where the loo is in relation to the user on mobile too.
