### ISSUE TITLE
Map vanishes when trying to enter fullscreen  (iPhone 5s)

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#268]
In a toilet report, I can zoom, then pan the map in the map thumbnail view. However if I press the full-screen button (I assume that's what it is - a dot in 4 corners) the map vanishes leaving white space where it was.

**Comment by Hoolean** [comment]
Hi @gailramster, is this the button you're referring to?

![Potential Button](https://user-images.githubusercontent.com/2150762/42996921-f33ad448-8c0c-11e8-980a-92d33e0d378f.png)

**Comment by gailramster** [comment]
Yes (I realise it's the full-screen button after trying on desktop - works really well nicely on desktop!)

**Comment by Hoolean** [comment]
We've got a range of quirks with fullscreen, so I've summarised them in #273; I'm going to close this issue.
