### ISSUE TITLE
Pin numbers not centred

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#269]
![fullsizeoutput_a07](https://user-images.githubusercontent.com/2690575/42994437-010dcb0e-8c06-11e8-8343-97e40a9fbd14.jpeg)

On iPhone 5s.

(The add a toilet and view map buttons are centred - they just look wrong in the screenshot due to me partially scrolling the view)

**Comment by Hoolean** [comment]
This looks like something I ran into yesterday (#265), although in a more common environment. I'll close this and document that it's broken by default on the iPhone 5S too in the older issue.
