### ISSUE TITLE
Find an appropriate strategy for editing Loo locations and implement it in the API

### ISSUE THREAD

**Issue by marxian** [neontribe/gbptm#27]

**Comment by RoboPython** [comment]
Implemented a couple of different ideas in the API, all of which have their issues. Currently trying to adjust front end to be more useful

**Comment by marxian** [comment]
I've made an amendment to this before shipping

1. We don't geolocate the positioning map if we are editing a loo! This prevents accidental repositionsing
2. We add "derivedFrom" to reports so that we can associate them with the loo we are editing. This actually moves the loo, rather than duplicating it

Deployed to prod
