### ISSUE TITLE
Customers only

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#270]
Can we delete this category from the drop-down list in 'who can access'? 
(And any reports that fall under it.)

Phases:

- [ ] Remove the value from the dropdown and associated places
- [ ] Clean up the data to remove these loos

**Comment by gailramster** [comment]
Without changing the fields this is tricky..

"Public toilet or private business?" is the best I can manage to align with the definition of the 2 categories, and the names we've given the fields
or
"public toilet or public use permitted"? would align with the definitions better, but may not match up in people's minds with the field options we give unless you can change the field name that's displayed from 'public' to read 'public toilet' without it being masses of work. 

you choose from those 2?

Definitions:
category 1 ('public') would cover all toilets people call a 'public toilet', i.e. public toilets but also station (train, bus, 'service..') toilets, and shopping centres (which are privately-run, technically, but feel like public space). 

Category 2 "non-customers permitted" = all other toilets the public can use - toilets in public buildings (hospitals, libraries); toilets in private buildings (cafes, supermarkets)...

**Comment by Hoolean** [comment]
Actually, with how the UI is setup, we can get away with changing the fields too, if that helps us get better-fit definitions (or, at least, the public facing part of them; we'd map them to the values in the database we have now).

Have you got any ideas on how we could improve the property with that restriction lifted?

**Comment by gailramster** [comment]
**Type of toilet? fields: Public toilet / toilet in public/private building** ( but we may get a lot of customer-only toilets, or worse)
**Public toilet or 'publicly accessible toilet'?** fields: public toilet / publicly accessible toilet - but doesn't explain the second term
**Type of toilet? fields: public toilet / other toilet public can access**
**Type of toilet? fields: public toilet / other (non-customers permitted)**

I think last is my fav but I'll keep thinking.

**Comment by gailramster** [comment]
Yes the last one, if fields aren’t too ling for you.
Though type of toilet? Or type of facility? Which would you expect to be asking what we’re asking, before seeing the fields?
