### ISSUE TITLE
'You are here' spot disappears on toilet report map

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#272]
Can it show on the Toilet Report map? It would make it easier to understand where the toilet is in relation to you, and to navigate to the toilet.

**Comment by Hoolean** [comment]
We just have a marker for the centre of the map at the moment, or do you mean something more like what is implemented in the old iteration of the toilet map?

At the moment, we have the `Get Directions` button for navigation. This takes users to their Maps app, which we hope would do a far better job of guiding them to a toilet (having specific directions, auto-updating their location, allowing them to specify what sort of transport, etc).

**Comment by Hoolean** [comment]
We work out the distance of loos from three types of location:

* Where the user is
* A place the user searches for
* A specific point chosen on the map

This is implemented by working out the distance of loos relative to where the map is centred; the user providing their location or searching for a place just changes the point the map is centred to as appropriate.

This works well, as:

* **It's quite intuitive for a user to use**
As soon as they move around, they have learnt how to find the nearest loos from any location
* **It's easy to indicate where the distances are calculated from**
We can just use the marker showing the centre of the map and there is no confusion between the three disparate sources of locations

That said, I think we've unearthed two issues here:

* **Where the locations are calculated from can seem ambiguous**
Having another icon for the user's location is definitely confusing in its current form, as it suggests that the location is being used more than it actually is; the locations aren't actually calculated from here directly after the map is moved. I think the solution to this is probably to remove the extraneous blue marker.
* **It's hard to keep track of where the locations were calculated from after you click on a loo**
As soon as you click on a loo, we stop showing where the distances were calculated from; maybe it would help to keep showing this marker and stop moving it? That way, if a user searches for loos around their location and clicks on a loo, they'll still be able to see where they were originally.

An alternative solution to both would be to stop using the centre of the map to calculate distances from and use something else instead, though I can't think immediately what would be as intuitive.

**Comment by gailramster** [comment]
My inclination is that the blue dot for location is both more useful and more familiar than the grey dot for map-centre so I wouldn't want to get rid of that. 

I think if you're less familiar with looking at maps, or the area you are in, it's easy to assume that the grey dot is a 'you are here' - which on a mobile it probably is (which is when this is most useful - but if the blue was showing two the two would overlay) but on a computer where you pan the screen more, it's not. 

A cross-hair would be more meaningful in terms of a map centre - would that be confusing with the other cross-hair for 'adding a toilet/editing a location' - probably not as that is also fixed in the map centre, so maybe it's the same thing. The blue dot and cross-hair would then overlay, and you'd see the cross-hair moving from the blue dot when you pan the map, showing how the centre is moving from where you are. That should make sense when you look back at the list view too, as then the distances are from 'where you are looking' not 'where you are'. 

I can see why the distance is useful though - less so on a computer where you can see the map and where you are in relation to the loos, but for people looking at the list view on a phone it's an immediate reality check of how far the various loos are... 

So I think a cross-hair would be better and more consistent.
