### ISSUE TITLE
On navigating directly to a loo's edit page, there is no information pre-filled into the form

### ISSUE THREAD

**Issue by Hoolean** [neontribe/gbptm#295]
## Problem

When navigating directly to a loo's edit page by URL, the form is not pre-filled with the existing data on the loo.

### Correct functionality

1. Navigate to [a loo page](https://gbptm-unity.herokuapp.com/loos/54c234af2ec4abe957b845db)
1. Press `Edit toilet`
1. The form is pre-filled with existing data on the loo

### Incorrect Functionality

1. Navigate directly by URL to [a loo's edit page](https://gbptm-unity.herokuapp.com/loos/54c234af2ec4abe957b845db/edit)
1. The form **isn't** pre-filled with existing data on the loo

**Comment by gailramster** [comment]
Just noticed this, now the edit button is restored on Admin tool (thanks for that). 
Would be great to get this fixed when you have a chance, so we can tidy up the data added since August from the publicity.

**Comment by marxian** [comment]
@gailramster This should be live now. Sorry for the wait.
