### ISSUE TITLE
Removed toilets don't disappear instantly

### ISSUE THREAD

**Issue by Hoolean** [neontribe/gbptm#296]
## Problem

When removing a toilet, it doesn't disappear straight away.

## Reproducing

1. Be authenticated
1. Remove a toilet
1. You are returned to the home screen, with the toilet you just removed still centered and selected

**Comment by stphnnnn** [comment]
This has been soft fixed by #529 because we no longer redirect to the index router after removing. 

A more detailed look at Apollo cacheing would inform a more robust fix in the future but for now this can be closed.
