### ISSUE TITLE
No toilets loading for some users - when no geolocating?

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#310]
I *think* when a user does not have geolocation enabled, toilets show in the initial Trafalgar Sq screen, but not once they have navigated via search to anywhere else. 
Two users reported this, and I replicated it when I followed a Facebook link (I don’t have location enabled on Fb, whereas I do on the browsers I use)
Image showing... no toilets. 

![dabab514-6da2-400b-bef5-1f5459ddbdf1](https://user-images.githubusercontent.com/2690575/43978292-a95c64a8-9cde-11e8-9fbe-854ea32a53cf.png)

**Comment by marxian** [comment]
@gailramster  Fixed!
