### ISSUE TITLE
No search box on Add a Toilet page

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#311]
mentioned this in the issue on 'search box evasive' but it's a separate thing. 

For UI it feels unhelpful that the search box is only on the home page and not on 'add a toilet' page, as if you want to add a toilet you might click 'Add a Toilet', then find no way of finding your toilet/location. 

Also unhelpful if you're adding a series of toilets and have to return to homepage between each one, though that probably only affects me/Phillip.

**Comment by marxian** [comment]
Rachel has also found this omission unhelpful

**Comment by marxian** [comment]
fixed!
