### ISSUE TITLE
Showing email addresses in contributor fields?

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#315]
I don't know if this is happening or if it's just the name.lastname format that Auth0 shows that he's referring to, but a user says 
"I don't understand why the source references are public. This means that contributors' email addresses are published and possibly harvested by spammers. This will put people off contributing".

Does make me think why do we show people's names, especially without letting them choose a username or what is shown or whether it's shown at all. FixMyStreet certainly lets you say yes/no each report whether you want your name public or not, which seems reasonable. 
Is this possible within Auth0?

**Comment by marxian** [comment]
The commenter is misinformed - it is only the first portion of the email address which we store and display.

I'd be delighted to not do this, and to remove contributor credits from the api output and from the UI.

We could follow FixMyStreet's lead on this - it adds complexity, but manage-ably so.
