### ISSUE TITLE
Android keyboard not clearing once Go selected (in Search)

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#317]
From user "on my mobile phone Galaxy J5(2016) Android 7.1.1 it is not clearing the 'transient keypad' in the lower part of the screen once 'Go' has been tapped (in Search). So the retrieved list cannot be accessed.”

**Comment by gailramster** [comment]
Update from user "I have just tried the web site on my mobile with 'Settings-Connections-Location ' set to ON and the display continues to show the 'transient' keyboard so the results cannot be seen (I also had my 'browser-extension-closeby' set to ON)."

**Comment by marxian** [comment]
Seems rather better now, after a bunch of library updates
