### ISSUE TITLE
Remove redundant properties

### ISSUE THREAD

**Issue by Hoolean** [neontribe/gbptm#318]
# Unused Properties

Some of the loo report properties in our schema have no UI and are barely used (if at all). It would be good to hear thoughts on whether we can remove all of these or if some have value.

## No UI, Seemingly Unused

|Property|Proportion Unknown|
|:-|-:|
|`architecturalInterest`|100%|
|`changingPlace`|100%|
|`familyToilet`|100%|
|`historicalInterest`|100%|
|`infoUrl`|100%|
|`reportEmail`|100%|
|`reportPhone`|100%|
|`parking`|99.8%|
|`disposal`|99.5%|
|`babyChangeLocation`|98.3%|
|`operator`|97.6%|

## No UI, Slightly Used

|Property|Proportion Unknown|
|:-|-:|
|`geocoded`|90.2%|
|`geocoding_method`|90.2%|
|`postcode`|88.5%|
|`streetAddress`|84.5%|

## Legacy

48.1% of loos have the legacy `orig` property. This contains the data that the loo report was derived from. It is of an unspecified schema. Unless we feel we are going to attempt to pull more information out of this that we haven't already, we should remove it from our database.

**Comment by marxian** [comment]
Great stuff.

I move to immediately remove the first category from our models and data.

`geocoded` and `geocoding_method` are vestiges of my old bulk-import system and can be removed in models and data.

`orig` is similar to `geocoded*` so long as we pull the whole dataset and archive it before we finally apply these transformations I think we should lose it.

@gailramster How do you feel about `postcode` and `streetAddress`? On the whole if we ever really needed them they could be derived from the lat/lng coordinates to some extent...

**Comment by gailramster** [comment]
Does Orig tell us if something was from OpenStreetMap or have we stored that info elsewhere?

No sentiment over postcode or street address, except Phillip does enter postcodes in the Notes to aid SatNavs - not something I think about in London. 
Postcode and some of the first set may be useful in future, but they can be deleted/dormant until we get to that point - all that info me and Phillip and any future employee will put in the notes.

**Comment by Hoolean** [comment]
Our `attribution` field in reports should tell us when we sourced our information from OpenStreetMap, so removing `orig` wouldn't cause any issues there.

From what has been said, I feel it's safe to remove all of these properties from our new schema, adding back properties only as needed in the future; if we regret this and need to refer back to past data, it will still be kept around.

**Comment by Hoolean** [comment]
Properties removed in new schema and migration code as of 00ef5bc328bf8317018ebcb6f06aafc7aed13af8.
