### ISSUE TITLE
Tidy tri-state properties

### ISSUE THREAD

**Issue by Hoolean** [neontribe/gbptm#319]
Some of our tri-state properties have instead six states:

* `undefined`
* `"Not Known"`
* `true`
* `"true"`
* `false`
* `"false"`

This is a pain: the string values are unneeded and confusing. Ideally, we'd just represent the three states as:

* `undefined` - the property is unknown
* `true` - the property is true
* `false` - the property is false

## Offending Properties

* `babyChange`
* `radar`
* `attended`
* `automatic`

**Comment by Hoolean** [comment]
Similarly to [filler property values](https://github.com/neontribe/gbptm/issues/320), it is hard to distinguish between when an undefined property indicates that a value from a previous report is being unset and when a report is just not trying to change the property. The resolution of #324 and #325 should make the difference clearer.

**Comment by Hoolean** [comment]
This will require the following mappings in [`migrate.js`](https://github.com/neontribe/gbptm/blob/55de406a477d91e1ab37362a20da222f379938ab/packages/migrate/src/migrate.js#L23-L51):

| From | To |
|---|---|
| `"true"` | `true` |
| `"false"` | `false` |
| `"Not Known"` | `null` |
| everything else | unchanged |

The reasoning behind mapping `"Not Known"` to `null` instead of `undefined` is that a report may express `"Not Known"` for two reasons:

0. The value is being given as a filler
0. The value was set in a previous report and is being unset

Setting the value to `null` takes care of case 2 and will be removed as redundant information in case 1, thus the value will end up as `undefined` in the finished loo.

**Comment by ob6160** [comment]
https://github.com/neontribe/gbptm/commit/5386d5507d1458e5cbca4bf3255423864d3dbcd2 maps values as specified in the table above.
