### ISSUE TITLE
Remove filler property values

### ISSUE THREAD

**Issue by Hoolean** [neontribe/gbptm#320]
We should be using a property's existence to signify whether a report contains useful information about it. Unfortunately, many reports populate a property but with an empty string. Such values contain no useful information and should be removed.

## Offending Properties

* `name`
* `access`
* `opening`
* `type`
* `accessibleType`
* `fee`
* `notes`

**Comment by marxian** [comment]
:+1:

**Comment by Hoolean** [comment]
5c2faca2681ee2363ac53f547bdd0357f34f97cb strips out values containing just whitespace from:

* `name`
* `access`
* `opening`
* `type`
* `accessibleType`
* `fee`
* `notes`
* **`removal_reason`**

When there is only whitespace present, the property is removed.

59e5d1c434b1732ed7b73065463b4ce455b51a09 adds validation to the freeform text fields to ensure that that they are not empty. Non-freeform fields will have this protection when they are restricted to an enum or are made tri-state.

**Comment by Hoolean** [comment]
Considering the chaining planned with #324, it needs to be ensured that such values were not in place to unset values from previous reports. This should be looked at again following the implementation of #324 and #325, as removing all empty values as we do now could have nasty side-effects.

**Comment by Hoolean** [comment]
6a19b6693b06434e02f6e6d8399a516a7bc2935c replaces empty values with `null`. It is then checked if a prior report gave a value for that property. If it did, the `null` is left in place as an indication of removal, otherwise, the property is redundant and so is removed.

This is yet to be implemented for values other than empty strings; this is really waiting on #319 and #326.
