### ISSUE TITLE
Use new schemas defined in the gbptm-loodb package in the API

### ISSUE THREAD

**Issue by ob6160** [neontribe/gbptm#377]
**Is your feature request related to a problem? Please describe.**
We need to transition towards using the new Loo/Report schemas defined in the loodb package in the API.

**Describe the solution you'd like**
* Old schemas for Loos and Reports to be replaced with the newly defined ones.
* Functionality of key routes should be preserved.

Note: Places where we consume data from the API will likely need to be changed as the schemas are very different to the legacy ones.

## Depends on:
https://github.com/neontribe/gbptm/issues/373

**Comment by Hoolean** [comment]
The deeper changes to property structure and the new relationship between loos and reports makes refactoring the API server, UI and admin front-end a lot of work.

An investigation into using the new schemas exists in [`377-api-use-schemas`](https://github.com/neontribe/gbptm/commits/377-api-use-schemas), where an experimental attempt to replace the old with the new was made.

From our experience trying this, things that would ease the transition:
* Tests ensuring that functionality is preserved after the migration
* Richer methods in `loodb` for loo (re)generation, facilitating updating the code that does this in the API server
* Working out which metadata outside of core loo properties should be preserved (e.g. the identity of the reporter is stored, credibility, etc), so it is known what should end up in the final UI

The code in the branch probably shouldn't be used in a future transition attempt, as it was quite fast moving and the schema is still to change significantly, but may be a good reference for a few of the parts that were implemented.
