### ISSUE TITLE
Data missing from Explorer

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#386]
**Describe the bug**
Some toilets on the map do not appear in the Search Results or in the Statistics by Area. (can't tell if they appear in overall Statistics). I noticed this a while ago, but have done more searching on problem time period now.

**To Reproduce**

https://www.toiletmap.org.uk/loos/5b58a7efb1a90a0011a5fd4a
This toilet - Leyton Library - was added by me about 4 months ago, prior to Auth0, along with several others. I logged in as Gail Ramster (my facebook profile I expect) and added this as a new loo. However when looking at all edits by Gail Ramster, this does not appear. Only edits that have another contributor (where I have edited an existing entry, rather than added a new toilet) appear, between the time period where Auth0 was installed (though that also means I stopped using this profile) until '2 years ago'. The Waltham Forest overall statistics and returned results also imply this data is not being counted there either.

1. Go to Search
2. Search 'Gail Ramster'
3. Scroll through to see the only edits attributed to Gail Ramster as ones were there is a second contributor, for any edits that are months or 1 year ago. 'New' toilets with only me as a contributor only start 2 years ago.
4. 'New' toilets from last 2 years are not appearing in the Explorer statistics or results. 

NOTE: There are also no new toilets created by GB Public Toilet Map (facebook?) since 12-APR-2017  (shown in results as '1 year ago') when they start appearing in returned results. There have been 1600 edits by GB Public Toilet Map of existing toilets since then, so 0 new toilets added by the same account isn't possible.
However this doesn't happen for PhillipW3032, where lots of toilets he has created appear in the explorer prior to 4 months ago. (could it be due to the means of logging in? Were we using different means in the OSM/FB/Twitter/Github options?)

**Screenshots**
<img width="1298" alt="screen shot 2018-11-28 at 10 36 15" src="https://user-images.githubusercontent.com/2690575/49146372-efdfcc00-f2f9-11e8-9789-aefa62bce342.png">

**Comment by marxian** [comment]
The example loo has moved to:

https://www.toiletmap.org.uk/explorer/loos/4b05a8684693dd1b2c76d370

**Comment by marxian** [comment]
CAn we check this against the staging version at https://gbptm.now.sh/explorer

**Comment by marxian** [comment]
@gailramster we believe the new areas system @jthistle built has resolved this, and produced significantly more accurate area data
