### ISSUE TITLE
American dates in Explorer

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#387]
**Describe the bug**
Entering Updated before and Updated After dates in Search on Explorer requires American Dates

**To Reproduce**
1. search 'updated after '08/08/2018' and 'updated before 08/09/2018' (1 month in UK)
Returns 60-odd results
2. search 'updated after 08/08/2018' and 'updated before 09/08/2018' (1 day in UK)
Returns 500+ results

**Expected behavior**
Flip day and month fields round please!

**Comment by jthistle** [comment]
This doesn't appear to happen anymore.
