### ISSUE TITLE
End to end test/Smoke test script 

### ISSUE THREAD

**Issue by jermyk** [neontribe/gbptm#391]
https://gbptm-stage.herokuapp.com/

**Smoke test for** https://gbptm.neontribe.now.sh/

**Location**

- [x] Does the toilet map recognise users location when accessing the site

- [x] User can see Use our Loos and Domestos logos 

- [x] User can see opt in with Google Analytics (In the footer menu on  mobile devices)

- [x] User can see opt in with Adobe Analytics (In the footer menu on  mobile devices)

- [x] User can save any changes and close the opt in page

**Comment by jermyk** [comment]
https://gbptm-stage.herokuapp.com/

- [ ] Does the toilet map recognise users location when accessing the site

- [ ] Select Add a toilet. User should be prompted to log in or sign up

- [ ]  If user has logged in before the site will tell them which email address they logged in with and allow them to progress

- [ ] If not the site will prompt them for email address and password details

**Adding a toilet**

**Comment by jermyk** [comment]
**Adding a toilet**

- [ ] Select Add a toilet option form the menu on the left of the page

- [ ] Follow the instructions for adding a toliet, remembering to use the crosshair to align the toilet to the map ansd  selecting the relevant name, facilities, notes and lat/long details if known. 

- [ ] Add the toilet to the map

- [ ] User should see a new green animated pin added to the map where the new toilet has been added

- [ ] Return to the home page by clicking on the GBTM logo at the top of the menu

- [ ] User should see the new toilet added as part of the nearest toilets option

- [ ] Total number of nearest toilets should still number 5

**Comment by jermyk** [comment]
**Preferences**

- [ ] Select the preferences link from the footer menu

- [ ] User should see a list of preferences they can select when searching for a toliet

- [ ] Select a specific requirement and save the changes

- [ ] Toilet map should display a message to show preferences have been updated

- [ ] Return to the homepage by selecting the GBTM logo at the top of the menu

- [ ] The User should now see a greater selection of toilets displaying on the map that when selected show the preferences the user updated

**Comment by jermyk** [comment]
**Privacy Policy**

- [ ] Select the privacy policy link in the footer menu

- [ ] User should see latest version of the GBPTM privacy policy and can scroll to the bottom of the page

**Comment by jermyk** [comment]
**About**

- [ ] Select the About link from the footer menu

- [ ] User should see information about the map

- [ ] User should see information - Use our Loos

- [ ] User should see information - Thinking about adding a toilet?

- [ ]

**Comment by jermyk** [comment]
**Removing a toilet**

- [ ] Select the toilet to be removed by double clicking the pn from the map

- [ ] Select edit toilet

- [ ] Scroll to the foot of the page

- [ ] Select Remove toilet

- [ ] Add some free text aas to why the toilet is being removed

- [ ] Click on the Remove it button

- [ ] When the user reactivate the map by clicking or dragging the pin should disappear

**Comment by jermyk** [comment]
**Open street map**

- [ ] Map renders and user can see "a map"

- [ ] User can drag the map up and down, left to right

- [ ] Map renders correctly when user drags as above

- [ ] Top left corner of the map should display + & - sign for zooming in and out

- [ ] Under the zoom icons a "show me where I am" figure should display

- [ ] Selecting by touch or clicking with a mouse on the "show me" figure should centre the map and a black cross should be visible in the centre of the users page

- [ ]  This should be the users current location

- [ ] Zoom in to this point to confirm this is correct

- [ ] User can zoom into a place on the map

- [ ] User can zoom out of a place on the map

- [ ] When user zooms out, more toilets in the area should appear

- [ ] Pins may display numbers corresponding to the number of toilets in that area

- [ ] Selecting a numbered pin should break out into the same number of individual pins (one for each toilet)

- [ ] Selecting a pin displays the toilet detail on the left of the page, and the edit option is available (see section for editing toilet)

- [ ] Zooming in reduces the number of pins visible and breaks down to individual toilets where applicable

- [ ] User may still numbered pins when zoomed in

- [ ] Selecting a pin when zoomed in displays the toilet information on the left of the pager

**Comment by jermyk** [comment]
**Search**

- [ ] The search icon and free text field should display in the top right hand corner of the page

- [ ] Click on/select the icon

- [ ] Option to add place name or postcode should display

- [ ] Add a valid postcode and hit enter

**Comment by jermyk** [comment]
Desktop - Windows 10 - Chrome

**Comment by jermyk** [comment]
**End of Test**

**Comment by jermyk** [comment]
@marxian 
Smoke tested on desktop and android device
One thing I noticed.
![Screenshot_050520_025715_PM](https://user-images.githubusercontent.com/4446325/81074291-b80e8800-8ee0-11ea-9bd5-58da14f954ae.jpg)

**Comment by marxian** [comment]
@jermyk @stphnnnn has just released a new version of the search widget which should address this!

**Comment by jermyk** [comment]
@marxian 
I'll check the above and progress any further issues in https://github.com/neontribe/gbptm/issues/652 which will supercede this ticket.
