### ISSUE TITLE
Second toilet appearing

### ISSUE THREAD

**Issue by jermyk** [neontribe/gbptm#392]
**Describe the bug**
After adding a toilet to a new place on the map. 
The user edits the details, and a second toilet appears in the same location.

**To Reproduce**
1. Go to 'Add a toilet'
2. Add detail and save changes
3. Edit the loo several times and save the changes each time.
4. A second toilet appears in the same place

**Screenshots**

**Desktop (please complete the following information):**
 - OS: **Windows 10**
 - Browser - **chrome** 

![screenshot_020519_102547_am](https://user-images.githubusercontent.com/4446325/52267210-67505e00-2930-11e9-92c9-4c673a84422c.jpg)

**Comment by ob6160** [comment]
Related PR: #400

**Comment by jermyk** [comment]
**Testing Details**

Toilet added to A147 St.Crispins Roundabout
![Screenshot_040319_094126_AM](https://user-images.githubusercontent.com/4446325/55465263-a62f2700-55f4-11e9-9021-4cc18f1639d0.jpg)

**Comment by jermyk** [comment]
![Screenshot_040319_094621_AM](https://user-images.githubusercontent.com/4446325/55465594-5b61df00-55f5-11e9-8087-8bbd12ae4bae.jpg)

**Comment by jermyk** [comment]
![Screenshot_040319_095740_AM](https://user-images.githubusercontent.com/4446325/55466349-ebecef00-55f6-11e9-901f-d270c6b03598.jpg)
@ob6160 
*Boo**
![Screenshot_040319_095846_AM](https://user-images.githubusercontent.com/4446325/55466442-12ab2580-55f7-11e9-9c4a-440a59d65f19.jpg)
