### ISSUE TITLE
Editing toilet not saving details

### ISSUE THREAD

**Issue by jermyk** [neontribe/gbptm#393]
**Describe the bug**
User was editing a new toilet details.
After a number of edits and saves, the user was no longer able to save the changes.
When inspecting the code an error displayed.
Screenshot attached 

**To Reproduce**
1. Go to 'Add a toilet'
2. Set up new toilet
3. Edit the detaIls and save changes 
4. Repeat this process, saving changes each time
5. When the changes cannot be saved inspect the console for the error message
6. Go to inspect/console to see error message

**Expected behavior**
There should be a list of errors displayed once the user cannot save changes anymore
**Screenshots**
![screenshot_020519_105426_am](https://user-images.githubusercontent.com/4446325/52268855-691c2080-2934-11e9-97de-79d8d7595654.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome,

**Comment by jermyk** [comment]
@marxian  fyi.

**Comment by ob6160** [comment]
pr up for fix in #403

**Comment by jermyk** [comment]
User was able to edit a new toilet successfully.
![Screenshot_040919_094629_AM](https://user-images.githubusercontent.com/4446325/55786561-619c0380-5aac-11e9-95b1-17cb67129865.jpg)

User was able to edit an existing toilet successfully.
