### ISSUE TITLE
User unable to see map after accessing https://www.toiletmap.org.uk/

### ISSUE THREAD

**Issue by jermyk** [neontribe/gbptm#402]
**Describe the bug**
User only sees a blank screen whan accessing https://www.toiletmap.org.uk/

![Screenshot_040419_115645_AM](https://user-images.githubusercontent.com/4446325/55550677-b87e9300-56d0-11e9-9062-40189706a645.jpg)

**Desktop (please complete the following information):**
 - 
 - Browser = IE11

**Comment by jermyk** [comment]
User oper![image](https://user-images.githubusercontent.com/4446325/55555135-693e5f80-56dc-11e9-9a3b-69929368f45d.png)

**Comment by jermyk** [comment]
Seems like Chrome is experiencing something similar.
I can hit other sites on the same browser instantly.
![Untitled_Clipping_040419_013036_PM](https://user-images.githubusercontent.com/4446325/55555717-d3a3cf80-56dd-11e9-8615-7c4791292870.jpg)

**Comment by jermyk** [comment]
@ob6160 

User has provided a screenshot as requested. 

![Screenshot_041519_113810_AM](https://user-images.githubusercontent.com/4446325/56126392-fbfbbb80-5f72-11e9-8817-53041c866673.jpg)

**Comment by jermyk** [comment]
@marxian @ob6160 

I was able to recreate this error on Big Red (on my desk) a windows 8 machine with IE11/Edge installed which we use for ARC browser testing.

![Screenshot_041719_040854_PM](https://user-images.githubusercontent.com/4446325/56299007-1a0c1c00-612b-11e9-9279-65c8501bcc00.jpg)

**Comment by jthistle** [comment]
One reason is that you need to give it location access before it will show you toilets.
