### ISSUE TITLE
Port Statistics to GraphQL

### ISSUE THREAD

**Issue by marxian** [neontribe/gbptm#407]
Displays such as https://www.toiletmap.org.uk/explorer/statistics currently depend on the rest endpoint defined here: https://github.com/neontribe/gbptm/blob/develop/packages/api/src/rest/statistics.js

We'd like to model this data in the schema and make it available through GraphQL.

I suggest that at the same time we try to tidy up the construction of the mongoose queries used here, and house them in methods on the models where they belong: https://github.com/neontribe/gbptm/blob/develop/packages/api/src/db/loo.js

**Comment by jthistle** [comment]
# Plan (WIP)

- Add a `counters` resolver to the schema
