### ISSUE TITLE
Non-www domain doesn't point to site

### ISSUE THREAD

**Issue by jthistle** [neontribe/gbptm#408]
**To Reproduce**
1. Visit https://toiletmap.org.uk.
2. The website doesn't load
3. Visit https://www.toiletmap.org.uk
4. The website _does_ load

**Expected behavior**
I expect the website to load correctly in both cases.

**Comment by jthistle** [comment]
@marxian ping :)

**Comment by jthistle** [comment]
Still an issue @marxian

**Comment by marxian** [comment]
@jthistle Y'know, after much messing with DNS settings  (and maybe a little unintended outage) I think this is working, finally, as intended.

Please confirm, ideally sometime on-or-after 24th Feb when the changes have propagated.

**Comment by jthistle** [comment]
I can confirm it now, actually - it seems to be working fine for me. Nice job! Closing this, I guess.
