### ISSUE TITLE
Search icon dissapears

### ISSUE THREAD

**Issue by jermyk** [neontribe/gbptm#409]
When the site is launched there is a working search icon in the top right but if you click on a toilet marker, the search icon in the top right dissapears and doesn't reappear unless you type the URL. 

![Screenshot_071919_020455_PM](https://user-images.githubusercontent.com/4446325/61537103-366f6b80-aa2e-11e9-9d3c-76d4b37ed11b.jpg)

![Screenshot_071919_020354_PM](https://user-images.githubusercontent.com/4446325/61537043-09bb5400-aa2e-11e9-8ed5-42ed832e86d8.jpg)

Edit: Also the return home button in the top left ,under the zoom in and out, dissapears after a toilet marker is clicked.

**Comment by jthistle** [comment]
I believe this is by design. It's explicitly written in the code to _not_ show the search bar on this page. I'm guessing that's because in the 'loo view' you're focussed on one loo - you don't really want people moving away from it.

**Comment by marxian** [comment]
Fixed
