### ISSUE TITLE
Website doesn't work on Internet explorer 11. (Windows 7).

### ISSUE THREAD

**Issue by jermyk** [neontribe/gbptm#410]
When trying to access the website on Internet Explore 11, a black screen appears.

![Screenshot_071919_022751_PM](https://user-images.githubusercontent.com/4446325/61538478-62402080-aa31-11e9-9d58-798f332e287a.jpg)

**Comment by marxian** [comment]
I've added another polyfil.

This is testable now on https://gbptm-stage.herokuapp.com

**Comment by jermyk** [comment]
@marxian 

I'm still unable to hit the site via IE11. 
I've tried both test and live versions. Both show the same results.

Screenshots showing comparisons to IE11 and Chrome for both sites.

![Screenshot_032720_030647_PM](https://user-images.githubusercontent.com/4446325/77770004-7f0b0a00-703c-11ea-8503-7312250587aa.jpg)

![Screenshot_032720_030836_PM](https://user-images.githubusercontent.com/4446325/77770169-c09bb500-703c-11ea-998f-d8c4705f995f.jpg)

**Comment by jermyk** [comment]
Error displayed.
![Screenshot_032720_031454_PM](https://user-images.githubusercontent.com/4446325/77770785-b75f1800-703d-11ea-82de-b7fdabf1ed66.jpg)
