### ISSUE TITLE
Suggest changing to HTTPS cloning

### ISSUE THREAD

**Issue by charlesstrange2** [neontribe/gbptm#426]
**Describe the bug**
README.md suggests using `git clone` in a manner that requires ssh. If the repo is public, we don't need ssh key based access controls, and should recommend a key-less mechanism, such as over HTTPS. 

Otherwise you get 
```
Cloning into 'gbptm'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Fail to setup keys for git, or do it wrong
2. Forget you've not setup keys for git
3. `git clone git@github.com:neontribe/gbptm.git gbptm`

**Expected behaviour**
repo clones to directory

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
n/a

**Comment by marxian** [comment]
@charlesstrange2 I'd rather not... Since https cloning doesn't sit well with 2FA or signed commits
