### ISSUE TITLE
Entirely deprecate REST

### ISSUE THREAD

**Issue by jthistle** [neontribe/gbptm#439]
We need to phase out REST. Note that the statistics REST api is already deprecated - we serve a notice instead of any data.

# Plan

- First, monitor requests to the API from external clients (i.e. not toiletmap.org.uk)

If there is a significant frequency of requests:

- Allow REST queries to continue, but serve a deprecation notice with each query
- Set a date for full deprecation and removal of the interface
- (possible) Provide documentation of how to query the new interface

If not:

- begin to immediately deprecate REST after `ui` has been switched over.

**Comment by marxian** [comment]
I've done some analysis.
As far as I can tell we have no remaining consumers of the REST api apart from ourselves.
The only formal consumer was "Ask Annie" and I think they are now mothballed.

Accordingly I've removed the REST interfaces from `develop`
