### ISSUE TITLE
Loos without areas

### ISSUE THREAD

**Issue by jthistle** [neontribe/gbptm#441]
There are loos in the database that have no area assigned to them. There seem to be quite a few, even active ones - try this query:

```mongodb
db.getCollection('newloos').find({
          'properties.area': { $exists: true },
          'properties.area.name': { $exists: true },
          'properties.area.type': { $exists: true },
          'properties.active': { $eq: true }
        })
```

**Comment by jthistle** [comment]
Hmmm, some of them seemed to have reports from Gail IIRC so I guess not. I'll check though.

**Comment by marxian** [comment]
closing, since it is contained in #404
