### ISSUE TITLE
Map location resetting after login in Auth0

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#454]
**Describe the bug**
The map location resetted to my location when I clicked 'Add a toilet'. 

**To Reproduce**
1. Go to a place on the map where you wish to add a toilet.
2. Click on Add a toilet
3. Sign in to Auth0
4. Browser returns to GBPTM but with map reset to your location. 

**Expected behavior**
We previously fixed a bug whereby clicking the 'Add a toilet' button would reset the location every time. It seems illogical and surprising to me that it did just reset the map when logging on first the first time. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Safari
 - Version 13

**Comment by marxian** [comment]
@jthistle Any ideas about how we'd tackle this?

It is responsible for a great deal of erroneous data. Folk mean to report a loo at their current map-location, hit "Add Loo" and then fill out and submit the form without realising that we've returned them to their geolocation.

Do you think it'd work to add the current lat/lng as query-string params to the return url passed to auth0?

**Comment by jthistle** [comment]
I will take a look at this issue when I have a moment.
