### ISSUE TITLE
wrong link in Explorer

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#472]
**Describe the bug**
The link under 'Search' in the Explorer Home Page (see Screenshot) is linking to https://www.toiletmap.org.uk/search, and not to https://www.toiletmap.org.uk/explorer/search.

**To Reproduce**
1. Go to toiletmap.org.uk
2. Click on the hyperlink text 'here' under Search
3. See error

![Screen Shot 2020-02-10 at 10 37 53](https://user-images.githubusercontent.com/2690575/74143005-e63a3f80-4bf1-11ea-9d2d-9d42a7f36a46.png)

**Desktop (please complete the following information):**
 - OS:  iOS
 - Browser Safari

**Comment by jthistle** [comment]
I'll take a look at this.
