### ISSUE TITLE
Explorer not showing all recent entries

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#473]
**Describe the bug**
I added 4 toilets (in Paris) over the weekend, e.g. https://www.toiletmap.org.uk/explorer/loos/2458896064b21c4f56379a60. 

These are not appearing in the search results. 

**To Reproduce**
1. Go to 'toiletmap.rca.ac.uk/explorer/search (automatically orders by most recent)
2. See four entries for weekend 8-9 Feb, none named Toilette or for area 'unknown' (outside GB). 

**Expected behavior**
Entries outside of unknown areas should still show. 

**Screenshots**
![Screen Shot 2020-02-10 at 10 50 25](https://user-images.githubusercontent.com/2690575/74143825-6b722400-4bf3-11ea-855b-896c999cdee0.png)
![Screen Shot 2020-02-10 at 10 27 15](https://user-images.githubusercontent.com/2690575/74143845-72009b80-4bf3-11ea-9724-0467cb8025aa.png)
![Screen Shot 2020-02-10 at 10 53 11](https://user-images.githubusercontent.com/2690575/74143894-93618780-4bf3-11ea-821f-f446c436d44f.png)

**Desktop**
 - OS:  iOS
 - Browser safari

**Additional context**
I added these as user gbtoiletmap@gmail.com, who has advanced login credentials (I can see usernames). However there are problems when I login with this address - see additional bug.

**Comment by marxian** [comment]
@gailramster confirmed

Fix is awaiting review.
