### ISSUE TITLE
Explorer search results not showing when logged in as gtoiletmap@gmail.com

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#474]
**Describe the bug**
Explorer search results not showing when logged in as gbtoiletmap@gmail.com. gbtoiletmap@gmail.com has advanced login credentials, meaning I can see usernames of who has added data, instead of results returning 'anonymous'

**To Reproduce**
1. Login as gbtoiletmap@gmail.com
2. Go to 'toiletmap.org.uk/explorer/search
3. See search fields briefly flash up, but whole page goes blank before search results appear. 

**Expected behavior**
Search results (most recent first) with usernames showing. 

**Screenshots**

![Uploading Screen Shot 2020-02-10 at 10.57.57.png…]()

**Desktop:**
 - OS:  iOS
 - Browser safari 13.0.5

**Comment by jthistle** [comment]
I hope that this will be fixed by GraphQL. At least, when I mocked advanced credentials for myself, it worked.

**Comment by gailramster** [comment]
I made a movie of it, and double-checked today - it does only happen with gbtoiletmap@gmail.com and not Gail.ramster@network.rca.ac.uk. The advanced credentials is the only difference I can think of. 
[IMG_1269.MOV.zip](https://github.com/neontribe/gbptm/files/4215984/IMG_1269.MOV.zip)
