### ISSUE TITLE
Problems with cross-component references?

### ISSUE THREAD

**Issue by marxian** [neontribe/gbptm#491]
**Describe the bug**

We're getting console warnings in local development:

```
Cannot update a component from inside the function body of a different component.
    in HomePage (at src/index.js:126)
    in Route (at src/index.js:123)
    in Switch (at src/index.js:122)
    in App (created by Context.Consumer)
    in withRouter(App) (at src/index.js:121)
    in Router (at Router.js:11)
    in Unknown (at src/index.js:120)
    in ApolloProvider (at src/index.js:119)
```
**To Reproduce**
Run the UI app in local development

**Expected behavior**
Probably we should address these

**Screenshots**

**Comment by jthistle** [comment]
https://github.com/facebook/react/issues/18178

**Comment by stphnnnn** [comment]
Updating to React and ReactDOM 16.13.1 doesn't seem to solve the problem but we do get a more descriptive error message:
```
Warning: Cannot update a component (`NearestLooMap`) while rendering a different component (`HomePage`). To locate the bad setState() call inside `HomePage`, follow the stack trace as described in https://fb.me/setstate-in-render
    in HomePage (at src/index.js:126)
    in Route (at src/index.js:123)
    in Switch (at src/index.js:122)
    in App (created by Context.Consumer)
    in withRouter(App) (at src/index.js:121)
    in Router (at Router.js:11)
    in Unknown (at src/index.js:120)
    in ApolloProvider (at src/index.js:119)
```

**Comment by stphnnnn** [comment]
Commenting out the highlighted mutation call removes the error but I'm not sure what the root of the problem is yet

<img width="791" alt="Screenshot 2020-03-25 at 13 35 05" src="https://user-images.githubusercontent.com/53346/77542012-729c7b00-6e9d-11ea-87ff-284a57447cc5.png">

**Comment by jthistle** [comment]
It might be an Apollo issue, then...
