### ISSUE TITLE
Problems responding to marker clicks

### ISSUE THREAD

**Issue by marxian** [neontribe/gbptm#531]
**Describe the bug**
By email from a frequent user:
"The site will display toilet locations but on PC (Out of date Firefox,) it won't display info on a location"

**To Reproduce**
Currently we can't replicate the problem

**Expected behavior**
Probably clicking loo markers should always navigate to the expected loo page

**Desktop (please complete the following information):**
 PC (OS Unknown)
Firefox
"Out of date"

**Comment by jthistle** [comment]
Can we not even get the Firefox version off of them?

**Comment by marxian** [comment]
Enquiries are underway :-)

**Comment by marxian** [comment]
Dupe of #532
