### ISSUE TITLE
Error when updating toilet details

### ISSUE THREAD

**Issue by jermyk** [neontribe/gbptm#547]
**Describe the bug**
Found as part of smoke testing on https://github.com/neontribe/gbptm/issues/391

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to **Edit toilet**
2. Add free text note
3. Save
4. See error ***Ooops, there was an error saving your change***

**Expected behaviour**
User expected the changes to be saved and display the next time the toilet was edited

**Screenshots**
![Screenshot_040120_021412_PM](https://user-images.githubusercontent.com/4446325/78142244-970bd080-7424-11ea-8147-d8d9ca525360.jpg)

**Desktop (please complete the following information):**
 - Windows 10
 - Browser - Chrome 
 - Version 80

**Comment by falconx** [comment]
Not reproducible for me on latest `master`.

**Comment by stphnnnn** [comment]
Same for me

**Comment by stphnnnn** [comment]
fixed by #618
