### ISSUE TITLE
Leaving the password reset page

### ISSUE THREAD

**Issue by jermyk** [neontribe/gbptm#549]
**Is your feature request related to a problem? Please describe.**
**On desktop**
After the user has reset their password, it's not obvious how to leave the page
There is a small star icon under the password reset copy which looks like it could be the way to leave the page.
![Screenshot_040220_111057_AM](https://user-images.githubusercontent.com/4446325/78236970-a21d3a00-74d2-11ea-89e3-b0a4bf430d8f.jpg)

 However when selected, this takes the user to  
![Screenshot_040220_111149_AM](https://user-images.githubusercontent.com/4446325/78237068-c0833580-74d2-11ea-9579-c9cb62512031.jpg)

On a mobile device the star icon is not active and if the user uses the back arrow to leave the page they are returned to the confimation email

**Describe the solution you'd like**
Add some help text telling the user how to leave the page and return to the toilet map

**Comment by stphnnnn** [comment]
Looks like we might be able to add a button to return to the application using this method: https://auth0.com/docs/universal-login/password-reset @marxian?

**Comment by marxian** [comment]
According to Auth0 they handle "Automatically redirecting the user after they reset their password"

@jermyk I guess this didn't happen for you?
