### ISSUE TITLE
wide cookie banner

### ISSUE THREAD

**Issue by marxian** [neontribe/gbptm#595]

**Comment by stphnnnn** [comment]
In #608 I've opted to not go full-width. These screenshots should illustrate why but it's easy enough to tweak sizing and positioning when the new designs come along 👍

Full-width:
<img width="1275" alt="Screenshot 2020-05-02 at 00 15 07" src="https://user-images.githubusercontent.com/53346/80860066-512d6c80-8c5d-11ea-8d08-4cdcdb7a1ef9.png">

Pull request implementation:
![Screenshot 2020-05-02 at 10 01 01](https://user-images.githubusercontent.com/53346/80860071-568ab700-8c5d-11ea-9318-de053ae17a2d.png)
