### ISSUE TITLE
Effects of Edit not visible until full reload

### ISSUE THREAD

**Issue by marxian** [neontribe/gbptm#599]
After saving changes in the edit form the changes are not reflected in the UI.

They turn up on a full page reload, which suggests an apollo cache problem.

**Comment by jthistle** [comment]
I thought I fixed this by putting [this block here](https://github.com/neontribe/gbptm/blob/1cbf3862ee62257d25fe5b1868d44d5334cebbad/src/pages/EditPage.js#L118) :/

**Comment by stphnnnn** [comment]
Interesting, I didn't spot that evict call but probably shouldn't be directly removing items from the cache before a mutation becuase if the mutation fails, we will be left with no data about that toilet.

Here's the Apollo docs which explains the approach in #602 to auto-updating the cached data after a succesful mutation.

I'll make another PR to remove the direct cache manipulation 👍
