### ISSUE TITLE
Babychanging data by area - active toilets

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#63]
The baby-changing column in the 'By Area' statistics of the Explorer is showing  # of baby-changing for all toilet reports when it should just show the 'active' toilet reports.  

Hopefully the headline stats also use 'active' toilets, not 'all' for baby-changing, accessible, public/restricted...?

**Comment by marxian** [comment]
@gailramster 

I this should be fixed on the next release.

I've adjusted the headlines to be proportional to active loos (except, obviously, the closed loos reports)
