### ISSUE TITLE
Delay between clicking on a marker and the marker being 'selected'

### ISSUE THREAD

**Issue by jthistle** [neontribe/gbptm#723]
**What happens**

When I click on a loo marker, there is a small delay (~0.3s) between my clicking and the marker entering a 'selected' state (i.e. becoming enlarged). This creates quite an unresponsive feeling. I suspect this is due to us waiting for info about the loo to load before we let it enter a 'selected' state.

**What I expect to happen**

When I click on a marker, the marker should become immediately selected. The info panel should then display a loading message while the necessary data is loaded.

**Comment by falconx** [comment]
It looks like we managed to address this at some point. Tested on a slow 3G connection and we appear to get instant feedback with the marker changing, whilst the details panel reads "Loading toilet...".
