### ISSUE TITLE
Opening Hours bug

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#73]
"Hi Gail

There's a bug in the map in that if you choose 'other' in the opening hours, it doesn't save it but just reverts to unknown.

Hope all is well

Phillip."

**Comment by marxian** [comment]
@gailramster 
So... It's been a while on this

I can't remember the intention behind the "other" entry in opening hours, can you?

I'm currently minded to remove it from the list?

**Comment by gailramster** [comment]
Most entries I put in are ‘other’ because they don’t fit the categories given. The ‘business hours’ category looks  and vague but behind the scenes it makes assumptions (9-5 perhaps), and lots are toilets, and businesses, are something else.

We could get rid of the ‘preferences’ though - don’t think our data is good enough for them to work effectively.

**Comment by marxian** [comment]
I guess we have (at least two) options:

1. We have a lot of code to support the "Open right now" preference feature. We could just drop the lot, and then allow free text in the "Opening Hours" field. This would certainly be liberating, but once we have free text there we'll never be able to provide a "Open right now" again...

2. We could continue to support the feature, but expand the possible selections, and revisit their descriptions.

**Comment by marxian** [comment]
Looking at the analytics, the preferences page was viewed 23k times by 15k people in the last year...
And 36k by 25k the year before.

So it does get _some_  repeated use...

**Comment by gailramster** [comment]
Ok, I’ll think about any short term improvements, like the opening hrs categories. Once we’ve overhauled the data we can review if it’s working well, rather than trashing good code.
