### ISSUE TITLE
LGA data

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#76]
Hello - Did you add this in the end? I can't spot it. I'm submitting the final data/story to the ODI on Monday for them to consider do if we can include it there's not much time left.

**Comment by marxian** [comment]
I've made another shot at this, and I'm importing from the dataset you prepared last year.

It seems a bit off. My test run generated 362 new entries and 160 errors out of the 1623 rows of data in the file.

I'm doing it again now, with some tweaks, into the database behind https://gbptm-stage.herokuapp.com

I initialised that database with a copy of the current production data as of about 6pm this evening.

You'll be able to compare the two datasets by  switching between "production" and "staging" in the settings screen of the admin tool.

I expect the import to complete at about 10.30ish this evening...

**Comment by gailramster** [comment]
Hello

Thanks. 

It seems to have only imported the councils that state they use WGS84 and not those using OSGB36? - comes to 383 toilets including Poole who don’t state what they use, with 231 new toilets.

Of the councils from that list that I’ve looked at, Poole, Mid Sussex, Plymouth, Lichfield seem to match OSM locations most of the time.

Hillingdon, Brent, Mid Suffolk, West Oxfordshire are a bit out causing duplications.

It seems hit and miss and likely that most of those new toilets risk being duplications where either the LGA data locates poorly (Hillingdon) or our existing data is in the wrong place (Plymouth).  I’d need to check through them using the GBPTM Analyser before they went ‘live’. If I edit the ‘staging’ dataset does that store my edits until they’re made live? I don’t want to spend time on it then find they’re written over if you tried importing LGA dataset (for the OSGB36 date or anything) again, in which case I can hold off. 

Is our de-duplicator still set at 20m? I think this was a mistake on my part - too restrictive.

It doesn’t seem like any of the councils in the LGA list feature as ‘best’ or ‘worst’ in any of our statistics so in that sense it won’t be obvious that they’re not included in the Production dataset at this point. It would be good if they were by November 18th so we’ve met that deliverable, but it depends how much correction work I’d need to do on it.. 

Gail.
