### ISSUE TITLE
Add a toilet box masks a lot of map

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#762]
Clicking 'add a toilet'. 
toilet entry box opens
Lots of white space masking a lot of the map.

Safari,
Version 13.1.1 (13609.2.9.1.3)

<img width="1440" alt="Screen Shot 2020-06-04 at 15 28 24" src="https://user-images.githubusercontent.com/2690575/83769732-22e5e700-a678-11ea-83ba-8119942ca006.png">
<img width="1440" alt="Screen Shot 2020-06-04 at 15 31 44" src="https://user-images.githubusercontent.com/2690575/83770185-abfd1e00-a678-11ea-8833-15c0f67face5.png">

**Comment by falconx** [comment]
Interesting observation. Perhaps the white rounded corners on the add/edit pages are misleading since, unlike the details panel, only a thin strip of the map is covered in this case.
