### ISSUE TITLE
Is this toilet free = Yes returning a ?

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#765]
I entered a new toilet selecting all fields to be 'yes'.

However the toilet appears as Free = ?

https://gbptm.now.sh/loos/21139711be6b9ae5d225a31e

Safari Version 13.1.1 (13609.2.9.1.3)
<img width="1436" alt="Screen Shot 2020-06-04 at 15 44 16" src="https://user-images.githubusercontent.com/2690575/83771542-4b6ee080-a67a-11ea-9dd4-b416fdd137a6.png">

**Comment by stphnnnn** [comment]
I can replicate this, it appears the add toilet mutation is not including the "noPayment" field, possibly because it doesn't change from the default
