### ISSUE TITLE
Toilet markers below the Filter window are not clickable. 

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#778]
Any toilet markers which appear below the filter window when viewed on desktop (Safari 13.1.1) are not clickable. 
The little finger cursor doesn't appear.

Is the filter window masking the part of the map beneath it?

![IMG_2545](https://user-images.githubusercontent.com/2690575/83798996-07410780-a69d-11ea-85bc-76c22b60b1f3.JPG)
![IMG_2546](https://user-images.githubusercontent.com/2690575/83799003-0a3bf800-a69d-11ea-9926-90939f3a7d73.JPG)

**Comment by marxian** [comment]
I've merged  #757 which is expected to fix this!
