### ISSUE TITLE
Re-wording of toilet details

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#822]
**Female Toilet** - reword to **Women** (no toilet)
**Male Toilet** - reword to **Men** (no toilet)
**Children only** - reword to **Children's toilet**

This needs fixing prior to launch, as female refers to the sex of the body, which excludes trans-women.  
Toilet needs omitting as we're not asking if there are women's toilets, just if there's are facilities women can access (could be gender-neutral). 
Children's toilets may not be an exclusive provision - if they are, it will be indicated by the 'access for women/men' fields being 'no'. 

On Add a toilet page:
**An all gender toilet?** - reword to **A gender neutral toilet?** - for consistency with filter

I think the order in which the icons appear should be the same as the order on the Add a Toilet form. That would put the woman/man/disabled icons at the top next to each other, as top line info. Current order is a bit random. 

However this is less urgent if difficult (could wait until after launch).

**Comment by marxian** [comment]
@gailramster Done!
