### ISSUE TITLE
Explorer Search opens of page 2 of results (results 11-20)

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#854]
Explorer Search opens of page 2 of results (results 11-20)
Pressing < to go to page 1 fails to load page. Going > to page 21-30 works correctly.

1. Toiletmap.co.uk/explorer
2. Click Search to https://www.toiletmap.org.uk/explorer/search
Screenshot 1 - the page that loads showing results 11-20
Screenshot 2 - pressing < to see results 1-10

![Screen Shot 2020-07-06 at 10 37 21](https://user-images.githubusercontent.com/2690575/86579079-b9a60c00-bf74-11ea-88c1-25a0b6826d2b.png)
![Screen Shot 2020-07-06 at 10 37 29](https://user-images.githubusercontent.com/2690575/86579084-bad73900-bf74-11ea-8459-f7524160ab61.png)

MacOS High Sierra
Safari 13.1.1

**Comment by marxian** [comment]
I smell an off-by-one error in the pagination display.
