### ISSUE TITLE
Toilet edit page resets if switch between browser tabs, losing edits. 

### ISSUE THREAD

**Issue by gailramster** [neontribe/gbptm#926]
When entering data for a toilet:
if you are trying to copy data between two tabs (or two browser windows, or even two different applications) when you go back to the source window it clears what you've just put in the GBPTM window.

e.g.
Click on https://www.toiletmap.org.uk/loos/71e1136d3075e5456ce5c780/edit
Change name of toilet or enter data in 'notes section'
Click on another tab
Click back to GBPTM tab - page on toilet appears to 'reload' losing changes. 

This is a big problem when entering data from other webpages such as councils, ie. mass manual data entry. 

Report from Phillip, who was hoping to get on with some serious data entry, reproduced by Gail.

**Comment by marxian** [comment]
Hi @gailramster,

@stphnnnn fixed this! I've merged the work and it should be deployed to production by the time you read this.

**Comment by gailramster** [comment]
Thanks @stphnnnn !
