### ISSUE TITLE
Zoom bug

### ISSUE THREAD

**Issue by harryharrold** [neontribe/gbptm#967]
**Describe the bug**
The zoom out wider than from around county level on the map using screen touch doesn't stay zoomed out, pops back in when touch is released.

**To Reproduce**
1. zoom out wider than from around county level on the map using screen touch
2. Release touch
3. Zoom does not persist,but pops back in.

**Expected behavior**
???

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - samsung note 4,
 -  android 6.0.1
 - Browser Unknown
 - Version Unknown

**Additional context**

N/A

**Comment by marxian** [comment]
This behaviour is intended, though clearly that could be better signalled.
We found that if we allowed a wide zoom folk would use it to examine toilet provision across the county, pacing an expensive strain on our infrastructure. We have plans to address this one day, but... You know.. Time..

In the meantime if you'd like to see a higher level overview we have an experimental chloropleth map at: https://www.toiletmap.org.uk/explorer/map

**Comment by marxian** [comment]
It'd be nice to think of a way to signal this. Perhaps we could detect the overzoom and pop a banner? "Looking to see _all_ the loos? Use our overview map and save the planet!"
